instancetype = "t2.micro"
amiID = "ami-0005e0cfe09cc9050"
instancename = "My_First_Instance"
regionname = "us-east-1"
bucket = "terraform-test-bucket"
dynamodb_table = "terraform-backend-table"
bucket_prefix = "my-terrafrom-s3-bucket"
